[book]
authors = ["hampus.avekvist@hey.com"]
language = "en"
multilingual = false
src = "docs"
title = "Asterisk ARI Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[output.html]
cname = "seffra.dev"
edit-url-template = "https://github.com/seffradev/arirs/edit/trunk/{path}"
git-repository-url = "https://github.com/seffradev/arirs"
preferred-dark-theme = "ayu"
smart-punctuation = true
