[book]
authors = ["hampus.avekvist@hey.com"]
language = "en"
multilingual = false
src = "docs"
title = "Asterisk Libraries in Rust Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[output.html]
cname = "seffra.dev"
edit-url-template = "https://github.com/seffradev/asterisk-rs/edit/trunk/{path}"
git-repository-url = "https://github.com/seffradev/asterisk-rs"
preferred-dark-theme = "ayu"
smart-punctuation = true
